"""PyTorch neural network modules for formed.

This package provides reusable PyTorch modules for building NLP models,
including embedders, encoders, and other building blocks.

"""

from .decoders import (
    BaseSequenceDecoder,
    BaseSequenceDecoderStateInitializer,
    LSTMDecoderState,
    LSTMSequenceDecoder,
    LSTMSequenceDecoderStateInitializer,
    ReorderableDecoderState,
    TransformerDecoderState,
    TransformerSequenceDecoder,
    TransformerSequenceDecoderStateInitializer,
)
from .embedders import AnalyzedTextEmbedder, BaseEmbedder, EmbedderOutput, TokenEmbedder
from .encoders import (
    BasePositionalEncoder,
    BaseSequenceEncoder,
    FeedForwardSequenceEncoder,
    GRUSequenceEncoder,
    LearnablePositionalEncoder,
    LSTMSequenceEncoder,
    ResidualSequenceEncoder,
    RotaryPositionalEncoder,
    SinusoidalPositionalEncoder,
    StackedSequenceEncoder,
    TransformerEncoder,
)
from .feedforward import FeedForward
from .losses import (
    BaseClassificationLoss,
    BaseRegressionLoss,
    BCEWithLogitsLoss,
    CrossEntropyLoss,
    MeanSquaredErrorLoss,
)
from .masks import BaseAttentionMask, CausalMask, CombinedMask, SlidingWindowAttentionMask
from .samplers import (
    AllBeamsFinishedTerminationPolicy,
    ArgmaxLabelSampler,
    BaseBeamSearchTerminationPolicy,
    BaseLabelSampler,
    BaseMultilabelSampler,
    BaseSequenceCandidateRule,
    BaseSequenceConstraint,
    BaseSequenceHypothesisScorer,
    BaseSequenceSampler,
    BaseSequenceSamplingAdapter,
    BaseSequenceScoreModifier,
    BaseSequenceStoppingCriterion,
    BeamSearchSequenceSampler,
    BeamSearchSequenceSamplerParams,
    BeamSearchTerminationContext,
    BernoulliMultilabelSampler,
    CumulativeLogProbabilityScorer,
    DefaultSequenceSamplingAdapter,
    EndOfSequenceStoppingCriterion,
    EnoughFinishedHypothesesTerminationPolicy,
    GreedySequenceSampler,
    LengthPenaltySequenceHypothesisScorer,
    MultinomialLabelSampler,
    SampledSequenceBatch,
    ScoreBoundTerminationPolicy,
    SequenceCandidateRuleUpdate,
    SequenceHypothesisScoringContext,
    SequenceSamplerOutput,
    SequenceSamplerParams,
    SequenceSamplingContext,
    SequenceSamplingModelOutput,
    SequenceSamplingModelParams,
    SequenceSamplingStepInput,
    SequenceSamplingStepOutput,
    SequenceTerminationReason,
    ThresholdMultilabelSampler,
    TopKMultilabelSampler,
)
from .states import ReorderableState
from .vectorizers import BagOfEmbeddingsSequenceVectorizer, BaseSequenceVectorizer
from .weighters import BalancedByDistributionLabelWeighter, BaseLabelWeighter, StaticLabelWeighter

__all__ = [
    # decoders
    "BaseSequenceDecoder",
    "BaseSequenceDecoderStateInitializer",
    "LSTMDecoderState",
    "LSTMSequenceDecoder",
    "LSTMSequenceDecoderStateInitializer",
    "ReorderableDecoderState",
    "ReorderableState",
    "TransformerDecoderState",
    "TransformerSequenceDecoder",
    "TransformerSequenceDecoderStateInitializer",
    # embedders
    "AnalyzedTextEmbedder",
    "BaseEmbedder",
    "EmbedderOutput",
    "TokenEmbedder",
    # encoders
    "BasePositionalEncoder",
    "BaseSequenceEncoder",
    "FeedForwardSequenceEncoder",
    "GRUSequenceEncoder",
    "LearnablePositionalEncoder",
    "LSTMSequenceEncoder",
    "ResidualSequenceEncoder",
    "RotaryPositionalEncoder",
    "SinusoidalPositionalEncoder",
    "StackedSequenceEncoder",
    "TransformerEncoder",
    # feedforward
    "FeedForward",
    # losses
    "BCEWithLogitsLoss",
    "BaseClassificationLoss",
    "BaseRegressionLoss",
    "CrossEntropyLoss",
    "MeanSquaredErrorLoss",
    # masks
    "BaseAttentionMask",
    "CausalMask",
    "CombinedMask",
    "SlidingWindowAttentionMask",
    # samplers
    "ArgmaxLabelSampler",
    "BaseLabelSampler",
    "BaseMultilabelSampler",
    "BaseBeamSearchTerminationPolicy",
    "BaseSequenceCandidateRule",
    "BaseSequenceConstraint",
    "BaseSequenceHypothesisScorer",
    "BaseSequenceSampler",
    "BaseSequenceSamplingAdapter",
    "BaseSequenceScoreModifier",
    "BaseSequenceStoppingCriterion",
    "AllBeamsFinishedTerminationPolicy",
    "BeamSearchSequenceSampler",
    "BeamSearchSequenceSamplerParams",
    "BeamSearchTerminationContext",
    "CumulativeLogProbabilityScorer",
    "BernoulliMultilabelSampler",
    "DefaultSequenceSamplingAdapter",
    "EndOfSequenceStoppingCriterion",
    "EnoughFinishedHypothesesTerminationPolicy",
    "GreedySequenceSampler",
    "LengthPenaltySequenceHypothesisScorer",
    "MultinomialLabelSampler",
    "SampledSequenceBatch",
    "SequenceCandidateRuleUpdate",
    "SequenceHypothesisScoringContext",
    "SequenceSamplerOutput",
    "SequenceSamplerParams",
    "SequenceSamplingContext",
    "SequenceSamplingModelOutput",
    "SequenceSamplingModelParams",
    "SequenceSamplingStepInput",
    "SequenceSamplingStepOutput",
    "SequenceTerminationReason",
    "ScoreBoundTerminationPolicy",
    "ThresholdMultilabelSampler",
    "TopKMultilabelSampler",
    # vectorizers
    "BagOfEmbeddingsSequenceVectorizer",
    "BaseSequenceVectorizer",
    # weighters
    "BalancedByDistributionLabelWeighter",
    "BaseLabelWeighter",
    "StaticLabelWeighter",
]
